tokens = [
    "<program>", "<import>", "<import>", "<more_import>", "<more_import>", "<import_prog>",
    "<more_importprog>", "<more_importprog>", "<import_next>", "<import_next>", "<global_declaration>",
    "<global_declaration>", "<more_globaldec>", "<more_globaldec>", "<global_statement>",
    "<global_statement>", "<global_statement>", "<global_statement>", "<function_prototype>",
    "<parameter>", "<parameter>", "<parameter>", "<more_param>", "<more_paramtail>", "<more_paramtail>",
    "<yeet_type>", "<yeet_type>", "<all_dtype>", "<all_dtype>", "<seq_dtype>", "<seq_dtype>", "<seq_dtype>",
    "<seq_dtype>", "<all_literal>", "<all_literal>", "<seq_literal>", "<seq_literal>", "<seq_literal>",
    "<seq_literal>", "<numeric_value>", "<numeric_value>", "<numeric_value>", "<numeric_value>",
    "<sheesh_declaration>", "<statement>", "<single_statement>", "<single_statement>", "<allowed_in_loop>",
    "<allowed_in_loop>", "<allowed_in_loop>", "<allowed_in_loop>", "<allowed_in_loop>", "<allowed_in_loop>",
    "<allowed_in_loop>", "<allowed_in_loop>", "<more_statement>", "<more_statement>", "<io_statement>",
    "<io_statement>", "<pa_mine_statement>", "<up_statement>", "<variable_declaration>", "<vardec_tail>",
    "<more_vardec>", "<more_vardec>", "<variable_assign>", "<variable_assign>", "<variable_reassign>",
    "<common_val>", "<common_val>", "<assign_value>", "<assign_value>", "<assign_value>", "<assign_value>",
    "<constant_declaration>", "<constant_declaration>", "<const_seq>", "<const_var>", "<const_tail>",
    "<more_const>", "<more_const>", "<assign_op>", "<assign_op>", "<assign_op>", "<assign_op>", "<assign_op>",
    "<assign_op>", "<function_invocation>", "<func_argument>", "<func_argument>", "<argument>", "<args_value>",
    "<more_args>", "<more_args>", "<control_flow_statement>", "<control_flow_statement>", "<kung_statement>",
    "<ehkung_statement>", "<deins_statement>", "<cond_tail>", "<cond_tail>", "<cond_tail>", "<more_condtail>",
    "<choose_statement>", "<when_statement>", "<statement_for_choose>", "<statement_for_choose>",
    "<more_when>", "<more_when>", "<choose_default>", "<choose_default>", "<looping_statement>",
    "<looping_statement>", "<bet_statement>", "<for_statement>", "<end_val>", "<for_initial_val>",
    "<for_initial_val>", "<for_initial_val>", "<for_initial_val>", "<step_statement>", "<step_statement>",
    "<loop_body>", "<loop_body_statement>", "<loop_body_statement>", "<loop_body_statement>",
    "<loop_body_statement>", "<more_loop_body>", "<more_loop_body>", "<loop_kung>", "<loop_ehkung>",
    "<loop_deins>", "<in_loop_condtail>", "<in_loop_condtail>", "<in_loop_condtail>", "<more_inloop_condtail>",
    "<loop_choose>", "<loop_when>", "<in_loop_when>", "<in_loop_when>", "<loop_default>", "<loop_default>",
    "<loop_control_statement>", "<loop_control_statement>", "<condition>", "<condition>", "<condition>",
    "<condition>", "<condition>", "<sequence_declaration>", "<seq_tail>", "<seq_tail>", "<seq_assign>",
    "<seq_assign>", "<seq_init>", "<seq_elem>", "<seq_elem>", "<seq_two-d_init>", "<seq_three-d_init>",
    "<seq_two-d_init>", "<seq_three-d_init>", "<seq_elem_value>", "<next_elem_value>", "<next_elem_value>",
    "<multi_seq>", "<more_seq>", "<more_seqtail>", "<more_seq>", "<seq_one_dim>", "<seq_two_dim>",
    "<seq_three_dim>", "<seq_two_dim>", "<seq_three_dim>", "<index>", "<seq_index_val>", "<seq_index_val>",
    "<seq_index_val>", "<seq_use>", "<seq_use_assign>", "<expression>", "<expression>", "<expression>",
    "<expression>", "<arithmetic_expression>", "<arithm_term>", "<arithm_factor>", "<arithm_factor>",
    "<arithm_tail>", "<arithm_addtail>", "<arithm_addtail>", "<arithm_term_tail>", "<arithm_mult_term>",
    "<arithm_mult_term>", "<add_op>", "<add_op>", "<mult_op>", "<mult_op>", "<mult_op>", "<relational_expression>",
    "<relational_expression>", "<relexrp_with_paren>", "<relexrp_without_paren>", "<relexrp_without_paren>",
    "<charr_val>", "<charr_val>", "<relop>", "<relop>", "<relop>", "<relop>", "<relop>", "<relop>",
    "<logical_expression>", "<logic_term>", "<logic_factor>", "<logic_factor>", "<logic_factor>", "<logic_tail>",
    "<logic_ortail>", "<logic_ortail>", "<logic_term_tail>", "<logic_andterm>", "<logic_andterm>",
    "<logical_not_expression>", "<logic_not_tail>", "<logic_not_tail>", "<logic_not>", "<logic_value>",
    "<logic_value>", "<logic_value>", "<logic_value>", "<logic_value>", "<text_concat>", "<concat_tail>",
    "<more_concat>", "<more_concat>", "<concat_val>", "<concat_val>", "<concat_val>", "<function_definition>",
    "<function_definition>", "<func_def>", "<more_funcdef>", "<more_funcdef>", "<yeet_statement>", "<yeet_statement>",
    "<return_value>", "<return_value>"
]

tokens = list(dict.fromkeys(tokens))
print(tokens)